---
tcp:
  routers:
    #   to-i7srv:
    #     service: i7srv
    #     rule: HostSNI(`*`)
    #     entryPoints:
    #       - websecure

    to-mongodb:
      service: mongodb
      rule: HostSNI(`*`)
      entryPoints:
        - mongodb
      tls:
        certresolver: letsencrypt
