http:
  middlewares:
    auth:
      basicAuth:
        usersFile: /etc/traefik/usersfile

    authelia:
      forwardAuth:
        address: http://authelia:9091/api/authz/forward-auth
        ## The following commented line is for configuring the Authelia URL in the proxy. We strongly suggest this is
        ## configured in the Session Cookies section of the Authelia configuration.
        # address: 'http://authelia:9091/api/authz/forward-auth?authelia_url=https%3A%2F%2Fauth.almeling.ru%2F'
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
        tls:
          ca: /certificates/ca.public.crt
          cert: /certificates/traefik.public.crt
          key: /certificates/traefik.private.pem

    authelia-basic:
      forwardAuth:
        address: http://authelia:9091/api/verify?auth=basic
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
        tls:
          ca: /certificates/ca.public.crt
          cert: /certificates/traefik.public.crt
          key: /certificates/traefik.private.pem
