## scp infra/traefik/dynamic/2*.yml root@almeling.ru:/share/infra/traefik/dynamic
http:
  middlewares:
    auth:
      basicAuth:
        usersFile: /etc/traefik/usersfile

    authelia:
      forwardAuth:
        address: http://authelia:9091/api/authz/forward-auth
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
