# scp infra/traefik/dynamic/3*.yml root@almeling.ru:/share/infra/traefik/dynamic
---
http:
  services:
    web:
      loadBalancer:
        servers:
          - url: http://whoami:80

    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000

    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080

    mongo:
      loadBalancer:
        servers:
          - url: http://mongo-express:8081

    pgadmin:
      loadBalancer:
        servers:
          - url: http://pgadmin:80

    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091
        serversTransport: autheliaMutualTLS
