---
http:
  services:
    web:
      loadBalancer:
        servers:
          - url: http://whoami:80

    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000

    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080

    mongo:
      loadBalancer:
        servers:
          - url: http://mongo-express:8081
