## scp infra/traefik/dynamic/4*.yml root@almeling.ru:/share/infra/traefik/dynamic
---
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certificates/almeling.ru.crt
        keyFile: /certificates/almeling.ru.key
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: almeling.ru
          sans:
            - "*.almeling.ru"
  options:
    modern:
      minVersion: VersionTLS13
    intermediate:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
