---
http:
  services:
    web:
      loadBalancer:
        servers:
          - url: http://whoami:80

    auth:
      loadBalancer:
        servers:
          - url: http://authelia:9091

    nocodb:
      loadBalancer:
        servers:
          - url: http://nocodb:8080

    pihole:
      loadBalancer:
        servers:
          - url: http://192.168.2.72:3001

    pgadmin:
      loadBalancer:
        servers:
          - url: http://192.168.2.72:15432

    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000

    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080

    traefik-fa:
      loadBalancer:
        servers:
          - url: http://traefik-fa:4181
