---
tcp:
  services:
    srv-tcp:
      loadBalancer:
        servers:
          - address: 192.168.2.91:22

    postgres-tcp:
      loadBalancer:
        servers:
          - address: 192.168.2.72:5432
