---
services:
  whoami:
    image: traefik/whoami
    container_name: $COMPOSE_PROJECT_NAME
    hostname: $COMPOSE_PROJECT_NAME
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
        reservations:
          cpus: 1
          memory: 256M
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
