---
services:
  mongodb:
    image: mongo:8.0.13
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    command: 'mongod --config /data/configdb/mongod.conf'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/db/mongo/configdb:/data/configdb
      - /share/db/mongo/data:/data/db
    env_file: stack.env
    networks:
      traefik-public:

  mongo-express:
    image: mongo-express:1.0.2
    container_name: m-express
    depends_on:
      - mongodb
    restart: always
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/db/mongo/mongo-express:/data/db
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
