---
services:
  mongodb:
    image: mongo:8.0.13
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    command: 'mongod --config /data/configdb/mongod.conf'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/db/mongo/configdb:/data/configdb
      - /share/db/mongo/data:/data/db
    env_file: stack.env
    networks:
      traefik-public:
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mongodb.entrypoints=mongodb
      - traefik.tcp.routers.mongodb.rule=HostSNI(`mongodb.almeling.ru`)
      - traefic.tcp.routers.mongodb.tls=true
      - traefik.tcp.routers.mongodb.tls.certresolver=letsencrypt
      - traefik.tcp.services.mongodb.loadBalancer.server.port=27017

  mongo-express:
    image: mongo-express:1.0.2
    container_name: m-express
    depends_on:
      - mongodb
    restart: always
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/db/mongo/mongo-express:/data/db
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
