## sudo docker compose -f /share/infra/portainer/data/compose/3/v7/docker-compose.yml up -d
## docker compose up -d
## docker compose down
---
services:
  traefik:
    image: traefik:v3.2.3
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/infra/traefik:/etc/traefik
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
