## sudo docker compose -f /share/infra/portainer/data/compose/3/v7/docker-compose.yml up -d
## docker compose up -d
## docker compose down
---
services:
  traefik:
    image: traefik:v3.5.3
    container_name: traefik
    hostname: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 5432:5432
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /share/infra/traefik:/etc/traefik
      - /share/infra/cert/traefik:/certificates
    networks:
      traefik-public: {}

networks:
  traefik-public:
    external: true
