## scp infra/traefik/traefik.yml root@almeling.ru:/share/infra/traefik
## http://localhost:8080/api/rawdata
---
entryPoints:
  mongodb:
    address: :27017

  postgres:
    address: :5432

  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
    proxyProtocol:
      insecure: false
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/14"
        - "192.168.0.0/16"
        - "fc00::/7"
    forwardedHeaders:
      insecure: false
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/14"
        - "192.168.0.0/16"
        - "fc00::/7"
  # metrics:
  #   address: :8082

api:
  dashboard: true
  insecure: false

global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    network: traefik-public
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

accessLog:
  format: json
  filePath: /logs/traefik_access.log
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: 10ms

log:
  level: INFO
  filePath: /logs/traefik.log
  format: json
  # maxSize: 10 # default 100mb (here logs managed through logrotate.d)

certificatesResolvers:
  letsencrypt:
    acme:
      email: sihuannewrise@gmail.com
      storage: /certificates/acme.json
      httpChallenge:
        entryPoint: web

metrics:
  prometheus: {}
