## path to place the file
## scp infra/traefik/traefik.yml root@almeling.ru:/share/infra/traefik
## http://localhost:8080/api/rawdata
---
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: almeling.ru
            sans:
              - traefik.almeling.ru
              - portainer.almeling.ru

api:
  dashboard: true
  insecure: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

accessLog: {}

log:
  level: DEBUG # or ERROR # set to INFO for production

certificatesResolvers:
  letsencrypt:
    acme:
      email: sihuannewrise@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
