## path to place the file
## scp infra/traefik/traefik.yml root@almeling.ru:/share/infra/traefik
## http://localhost:8080/api/rawdata
---
entryPoints:
  mongodb:
    address: :27017

  postgres:
    address: :5432

  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: almeling.ru
            sans:
              - "*.almeling.ru"
    # proxyProtocol:
    #   insecure: false
    #   trustedIPs: []
    # forwardedHeaders:
    #   insecure: false
    #   trustedIPs: []

api:
  dashboard: true
  insecure: false
  # insecure: true # Don't do this in production

global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    network: traefik-public
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

accessLog:
  format: json
  filePath: /logs/traefik_access.log
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: 10ms

log:
  level: INFO # DEBUG or ERROR set to INFO for production
  filePath: /logs/traefik.log
  format: json
  # maxSize: 10 # default 100mb

certificatesResolvers:
  letsencrypt:
    acme:
      email: sihuannewrise@gmail.com
      storage: /certificates/acme.json
      dnsChallenge:
        provider: selectelv2
