## path to place the file
## scp infra/traefik/traefik.yml root@almeling.ru:/share/infra/traefik
## http://localhost:8080/api/rawdata
---
entryPoints:
  mongodb:
    address: :27017
  postgres:
    address: :5432
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443

api:
  dashboard: true
  insecure: true # Don't do that in production

global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    network: traefik-public
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

accessLog: {}

log:
  level: DEBUG # or ERROR # set to INFO for production

certificatesResolvers:
  letsencrypt:
    acme:
      email: sihuannewrise@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
