## scp infra/redis/redis.conf root@almeling.ru:/share/db/redis/conf
---
services:
  redis:
    image: redis:alpine3.22
    container_name: redis
    hostname: redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/db/redis/conf:/etc/redis
      - /share/db/redis/data:/data
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
