---
services:
  redis:
    image: redis:alpine3.22
    container_name: redis
    hostname: redis
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/db/redis/conf:/etc/redis
      - /share/db/redis/data:/data
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
