---
services:
  redis:
    image: redis:8.2.2
    container_name: redis
    hostname: redis
    restart: always
    env_file: stack.env
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command:
      [
        "redis-server",
        "/etc/redis/redis.conf",
        "--bind",
        "redis",
        "--port",
        "6379",
      ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/db/redis/conf:/etc/redis
      - /share/db/redis/data:/data
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
