---
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/infra/auth/authelia/config:/config
      - /share/infra/auth/authelia/secrets:/secrets
      - /share/infra/auth/authelia/cert:/certificates
    networks:
      traefik-public: {}

networks:
  traefik-public:
    external: true
