---
services:
  authelia:
    image: authelia/authelia:4.39.13
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/infra/authelia/config:/config
      - /share/infra/authelia/secrets:/secrets
    networks:
      traefik-public:

networks:
  traefik-public:
    external: true
