---
services:
  authelia:
    image: docker.io/authelia/authelia:latest
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - /share/infra/auth/authelia/config:/config
      - /share/infra/auth/authelia/secrets:/secrets
    networks:
      traefik-public:


networks:
  traefik-public:
    external: true
