# scp infra/authelia/configuration.yml root@almeling.ru:/share/infra/authelia/config
---
server:
  address: tcp://0.0.0.0:9091
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

log:
  level: debug

totp:
  issuer: almeling.ru

# identity_validation:
#   reset_password:
#     jwt_secret: "a_very_important_secret"

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: "pgadmin.almeling.ru"
      policy: "bypass"
    - domain: "traefik.almeling.ru"
      policy: one_factor
    # - domain: "secure.almeling.ru"
    #   policy: "two_factor"

session:
  # secret: "insecure_session_secret"
  cookies:
    - name: authelia_session
      domain: almeling.ru
      authelia_url: https://auth.almeling.ru
      expiration: "1 hour"
      inactivity: "5 minutes"
      default_redirection_url: https://almeling.ru

regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  # encryption_key: "you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this"
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
