# scp infra/authelia/configuration.yml root@almeling.ru:/share/infra/authelia/config
---
server:
  address: tcp://0.0.0.0:9091
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

log:
  level: debug

totp:
  issuer: almeling.ru

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: almeling.ru
      policy: one_factor    # bypass or two_factor
    - domain: pgadmin.almeling.ru
      policy: one_factor
    - domain: traefik.almeling.ru
      policy: one_factor

session:
  cookies:
    - name: authelia_session
      domain: almeling.ru
      authelia_url: https://auth.almeling.ru
      expiration: "1 hour"
      inactivity: "5 minutes"
      default_redirection_url: https://almeling.ru

regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  postgres:
    address: tcp://postgres:5432
    database: auth
    username: auth
    schema: "public"
    timeout: "5 seconds"

notifier:
  filesystem:
    filename: /config/notification.txt
